server:
  port: 9001

spring:
  thymeleaf:
    cache: false
    content-type: text/html
    mode: LEGACYHTML5
  #关闭缓存
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/seckill?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      #空闲连接存货最大时间，默认10分种
      idle-timeout: 100000
      #最大连接数
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      max-lifetime: 1000000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    druid:
      test-on-borrow: true
      test-while-idle: true

#  #数据库
#  redis:
#    host: 101.35.230.76
#    port: 6379
#    database: 0
#    timeout: 10000ms
#    lettuce:
#      pool:
#        #最大连接数
#        max-active: 8
#        #最大连接阻塞等待时间，默认-1
#        max-wait: 10000ms
#        #最大空闲连接，默认8
#        max-idle: 200
#        #最小空闲连接时间
#        min-idle: 5
#    password: 123456
#  web:
#    resources:
#      add-mappings: true
#      cache:
#        cachecontrol:
#          #缓存响应时间
#          max-age: 3600
#      chain:
#        #启用缓存
#        cache: true
#        #启用资源链
#        enabled: true
#        # 启用压缩资源
#        compressed: true
#        # 启用h5应用缓存
#      static-locations: classpath:/static/
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只能处理一条消息，处理完才能处理下一条
        prefetch: 1
        #是否默认启动容器
        auto-startup: true
        #是否重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #是否重试
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000ms
        #重试最大次数默认3次
        max-attempts: 3
        #重试最大间隔时间默认10000ms
        max-interval: 10000ms
        #重试间隔乘数，比如配置2.0，第一次10s 第二次20s
        multiplier: 1
    publisher-confirm-type: correlated
    publisher-returns: true

mybatis-plus:
  # 配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.example.seckilldemo.pojo

logging:
  level:
    com.example.seckilldemo.mapper: debug

